apiVersion: v1
kind: Service
metadata:
  name: js-dwn-service
spec:
  type: LoadBalancer
  selector:
    app: js-dwn
  ports:
    - name: dwn
      protocol: TCP
      port: 1337
      targetPort: 1337
    - name: ipfs-1
      protocol: TCP
      port: 4002
      targetPort: 4002
    - name: ipfs-2
      protocol: TCP
      port: 4003
      targetPort: 4003
